version: '3'

services:
  sonarqube:
    image: sonarqube
    ports:
      - "80:9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
    depends_on:
      - postgres
    networks:
      - sonarnet

  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sonarnet

networks:
  sonarnet:

volumes:
  sonarqube_data:
  postgres_data: