kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/default.tmpl'
    route:
      receiver: alert-emailer
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 10m
    receivers:
    - name: alert-emailer
      email_configs:
      - to: 'grafanaprometheus76@gmail.com'
        from: 'grafanaprometheus76@gmail.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'grafanaprometheus76@gmail.com'
        auth_password: 'gfmm esqe agrb zejx'