apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-metrics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-metrics
  template:
    metadata:
      labels:
        app: custom-metrics
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: custom-metrics-service
        image: testleaf/selenium-grid-queue-size
        env:
        - name: GRID_IP
          value: "20.244.41.195" 
        - name: GRID_PORT
          value: "32000" 
        livenessProbe:
          httpGet:
            path: /metrics
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /metrics
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: custom-metrics-service
spec:
  selector:
    app: custom-metrics
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000