dockerfile 
# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set working directory in container
WORKDIR /app

# Copy the current directory contents into the container
COPY . /app

# Install any needed packages
RUN pip install --trusted-host pypi.python.org requests prometheus_client

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Run the Python script when the container launches
CMD ["python", "selenium_grid_metrics.py"]

